language: python
python:
  - '3.6' 
install:
  - pip install -r requirements.txt
# script: python test_example.py  # 如果有单元测试这里应该执行单元测试
deploy:
  provider: pypi
  user: taitai351     
  script: true
  password: c3562019  
    python: 3.6
    tags: true
    branch: master

